[package]
name = "iron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-graphql = { version = "6.0.4", features = ["tracing", "uuid"] }
async-graphql-axum = "6.0.4"
axum = { version = "0.6.20", features = ["macros", "tracing"] }
axum-server = { version = "0.5.1", features = ["tls-rustls"] }
entity = { path = "../database/entity" }
env_logger = "0.10.0"
rustls = "0.21.6"
rustls-pemfile = "1.0.3"
sea-orm = { version = "^0", features = ["sqlx-sqlite", "runtime-tokio-rustls", "macros", "debug-print", "with-uuid", "with-chrono"] }
tokio = { version = "1.32.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.4.3", features = ["full"] }
tracing = "0.1.37"
uuid = "1.4.1"
velcro = "0.5.4"
