//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "game_server")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::minecraft_server::Entity")]
    MinecraftServer,
    #[sea_orm(has_many = "super::paper_mc_server::Entity")]
    PaperMcServer,
}

impl Related<super::minecraft_server::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MinecraftServer.def()
    }
}

impl Related<super::paper_mc_server::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaperMcServer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
