//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "minecraft_server")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub game_type: String,
    pub game_version: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::game_server::Entity",
        from = "Column::Id",
        to = "super::game_server::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GameServer,
    #[sea_orm(
        belongs_to = "super::game_type::Entity",
        from = "Column::Id",
        to = "super::game_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GameType2,
    #[sea_orm(
        belongs_to = "super::game_type::Entity",
        from = "Column::GameType",
        to = "super::game_type::Column::TypeName",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    GameType1,
    #[sea_orm(has_many = "super::minecraft_jvm_argument::Entity")]
    MinecraftJvmArgument,
    #[sea_orm(has_many = "super::minecraft_server_type::Entity")]
    MinecraftServerType,
    #[sea_orm(has_many = "super::paper_mc_server::Entity")]
    PaperMcServer,
}

impl Related<super::game_server::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameServer.def()
    }
}

impl Related<super::minecraft_jvm_argument::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MinecraftJvmArgument.def()
    }
}

impl Related<super::minecraft_server_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MinecraftServerType.def()
    }
}

impl Related<super::paper_mc_server::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaperMcServer.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
