//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

pub use super::game_server::Entity as GameServer;
pub use super::minecraft_server::Entity as MinecraftServer;
pub use super::paper_mc_server::Entity as PaperMcServer;
