//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::game_server::Entity as GameServer;
pub use super::game_type::Entity as GameType;
pub use super::minecraft_jvm_argument::Entity as MinecraftJvmArgument;
pub use super::minecraft_server::Entity as MinecraftServer;
pub use super::minecraft_server_type::Entity as MinecraftServerType;
pub use super::paper_mc_server::Entity as PaperMcServer;
