//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "minecraft_server")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub server: String,
    pub game_version: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::paper_mc_server::Entity")]
    PaperMcServer,
    #[sea_orm(
        belongs_to = "super::server_host::Entity",
        from = "Column::Server",
        to = "super::server_host::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    ServerHost,
}

impl Related<super::paper_mc_server::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaperMcServer.def()
    }
}

impl Related<super::server_host::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServerHost.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
